apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-client-config
data:
  NODE_LIST: "cache-node-0.cache-svc:8080,cache-node-1.cache-svc:8080,cache-node-2.cache-svc:8080,cache-node-3.cache-svc:8080,cache-node-4.cache-svc:8080"
